Explorer/Models/CreateDB.cs
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;

namespace Explorer.Models
{
    public class CreateDB
    {
        private byte[] data;

        // иконки расширений файлов для БД
        public string StringData { get; set; }
        public byte[] ByteData
        {
            set
            {
                data = value;
                StringData = string.Join(".", data.Select(p => p.ToString()));
            }
        }

        private readonly ExplorerEntities context;
        private int foldId;
        private int typeId;

        readonly Dictionary<string, int> extCoList = new Dictionary<string, int>();
        readonly Dictionary<string, int> foldList = new Dictionary<string, int>();
        
        public CreateDB(string rootDir)
        {
            context = new ExplorerEntities();
            AddDataDb(rootDir);
        }

        private void AddDataDb (string startDir)
        {
            var di = new DirectoryInfo(startDir);
            var fsItems = di.GetFileSystemInfos()
                .OrderBy(f => f.Name)
                .ToList();

            foreach (var fsItem in fsItems)
            {
                if (fsItem.IsDirectory())
                {
                    AddFolder(fsItem);
                    AddDataDb(fsItem.FullName);
                }
                else
                {
                    AddExtension(fsItem);
                    AddFile(fsItem);
                }
            }
        }

        private void AddExtension(FileSystemInfo fsItem)
        {

            string ext = fsItem.Extension;
            var ico = Icon.ExtractAssociatedIcon(fsItem.FullName);
            var sz = ico.Size;
            ByteData = PictureToBytes(ico);

            if (!extCoList.ContainsKey(ext))
            {
                FileExtentions newFileExtension = new FileExtentions()
                {
                    Type = ext,
                    Icon = StringData
                };

                context.FileExtentions.Add(newFileExtension);
                context.SaveChanges();

                typeId = newFileExtension.TypeFileId;
                extCoList.Add(ext, typeId);
                return;
            }

            extCoList.TryGetValue(ext, out typeId);

        }

        private void AddFile(FileSystemInfo fsItem)
        {
            string parent = new DirectoryInfo(fsItem.FullName).Parent?.Name;

            Files newFile = new Files()
            {
                Name = fsItem.FullName,
                FolderId = foldId,
                TypeFileId = typeId,
                Description = string.Format($"Файл {fsItem.Extension}"),
                Content = ""
            };

            context.Files.Add(newFile);
            context.SaveChanges();

            newFile.FolderId = CheckParent(parent, newFile.FileId);
            context.SaveChanges();

        }

        private void AddFolder(FileSystemInfo fsItem)
        {
            string parent = new DirectoryInfo(fsItem.FullName).Parent?.Name;

            Folders newFolder = new Folders()
                {
                    Name = fsItem.Name
                };

                context.Folders.Add(newFolder);
                context.SaveChanges();

                foldId = newFolder.FolderId;
                Folders fld = context.Folders
                    .FirstOrDefault(p => p.Name == fsItem.Name);

                fld.ParentFolderId = CheckParent(parent, foldId);

                context.SaveChanges();

                foldId = newFolder.FolderId;
                foldList.Add(fsItem.Name, foldId);
        }
        // erwewe
        private int CheckParent(string parent, int defId)
        {
            if (!foldList.ContainsKey(parent))
            {
                return defId;
            }

            foldList.TryGetValue(parent, out int idParent);
            return idParent;
        }

        private static byte[] PictureToBytes(Icon icon)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                icon.Save(ms);
                return ms.ToArray();
            }
        }
    }

    public static class FileSystemInfoExtensions
    {
        public static bool IsDirectory(this FileSystemInfo fsItem)
        {
            return (fsItem.Attributes & FileAttributes.Directory) == FileAttributes.Directory;
        }
    }
}

Explorer/Models/TreeViewModel.cs
namespace Explorer.Models
{
    public class TreeViewModel
    {
        public string id { get; set; }
        public string parent { get; set; }
        public string text { get; set; }
        public string icon { get; set; }
        public string state { get; set; } //opened, disabled, selected
        public string li_attr { get; set; }
        public string a_attr { get; set; }
    }
}

Explorer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Explorer.Models;
using System.Web.Script.Serialization;

namespace Explorer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ExplorerEntities newContainer = new ExplorerEntities();
            bool exDb = newContainer.Database.CreateIfNotExists();
            if (exDb || !newContainer.Folders.Any())
            {
                 new CreateDB(AppDomain.CurrentDomain.BaseDirectory);
            }
            return View();
        }
    }
}

Explorer/Controllers/TreeModelController.cs
using Explorer.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Explorer.Controllers
{
    public class TreeModelController : Controller
    {
        public string StringData { get; set; }
        public byte[] ByteData => Array.ConvertAll(StringData.Split('.'), byte.Parse);

        // GET: TreeModel
        public async Task<ActionResult> Index()
        {
            ExplorerEntities newContainer = new ExplorerEntities();
            bool exDb = newContainer.Database.CreateIfNotExists();
            if (exDb || !newContainer.Folders.Any())
            {
                new CreateDB(AppDomain.CurrentDomain.BaseDirectory);
            }

            //Заполнение структуры дерева из БД
            IList<TreeViewModel> data = GetTreeData();

            ViewBag.Json = new JavaScriptSerializer().Serialize(data);
            return View();
        }

        private List<TreeViewModel> GetTreeData()
        {
            List<TreeViewModel> nodes = new List<TreeViewModel>();
            using (ExplorerEntities context = new ExplorerEntities())
            {
                string pathIconFolder = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content", "images",
                    "folder_closed_16x16.png");
                var byteIconFold = PictureToBytes(new Bitmap(pathIconFolder));
                var strIconFold = "data:image/gif;base64," + Convert.ToBase64String(byteIconFold);

                int idLast = 0;
                foreach (var item in context.Folders)
                {
                    idLast = item.FolderId;
                    nodes.Add(new TreeViewModel
                    {
                        id = item.FolderId.ToString(),
                        parent = item.ParentFolderId == item.FolderId ? "#" : item.ParentFolderId.ToString(),
                        text = new DirectoryInfo(item.Name).Name,
                        icon = strIconFold,
                    });
                }

                foreach (var item in context.Files)
                {
                    var itemExt = context.FileExtentions.First(e => e.TypeFileId == item.TypeFileId);
                    StringData = itemExt.Icon;
                    var iconExt = "data:image/gif;base64," + Convert.ToBase64String(ByteData);

                    nodes.Add(new TreeViewModel
                    {
                        id = (++idLast).ToString(),
                        parent = item.FolderId == item.FileId ? "#" : item.FolderId.ToString(),
                        text = new DirectoryInfo(item.Name).Name,
                        icon = iconExt,
                    });
                }
            }

            return nodes;
        }

        public static byte[] PictureToBytes(Image img)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                img.Save(ms, ImageFormat.Gif);
                return ms.ToArray();
            }
        }

        public ActionResult Tree()
        {
            return View();
        }
    }
}

Explorer/Views/Home/Index.cshtml
<div class="row">
    <div class="card card-tree">
        <div class="card-body">
            <div id="object-children-tree">
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
        $(document).ready(function () {
            $('#jstree').jstree({ 
                "core" : {
                    "data" : ""
                }
            });
        });
    </script>

    <div class="card card-content">
        <div class="card-header">
            <div class="tabs">
                <input type="radio" name="tab-btn" id="tab-btn-1" value="" checked>
                <label for="tab-btn-1">File 1</label>
                <input type="radio" name="tab-btn" id="tab-btn-2" value="">
                <label for="tab-btn-2">File 2</label>
                <input type="radio" name="tab-btn" id="tab-btn-3" value="">
                <label for="tab-btn-3">File 3</label>

                <div id="content-1">
                    Content 1
                </div>
                <div id="content-2">
                    Content 2
                </div>
                <div id="content-3">
                    Content 3
                </div>
            </div>
        </div>
    </div>
</div>

Explorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проводник</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
@using System.IO
<body style="background-color: #f5f5f5">
<header>
    <div class="container menu">
        @Html.ActionLink("Создать Папку", "Tree", "TreeModel")
        @Html.ActionLink("Удалить Папку", "Index", "TreeModel")
        @Html.ActionLink("Загрузить файл", "Index", "TreeModel")
        @Html.ActionLink("Скачать файл", "Index", "TreeModel")
        @Html.ActionLink("Удалить Файл", "Index", "TreeModel")
    </div>
</header>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Проводник</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

Explorer/Views/TreeModel/Index.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
@*<link rel="stylesheet" href="dist/themes/proton/style.css"/>*@

<div class="row">
    <div class="card card-tree">
        <div class="card-body">
            <div id="jstree"></div>
        </div>
    </div>

    <script type="text/javascript">
        $('#jstree').jstree({
            "core": {
                "animation": 0,
                "check_callback": true,
                'force_text': true,
                'data': @Html.Raw(ViewBag.Json)
            },
            "plugins": ["state", "unique", "types", "wholerow"]
        });
    </script>

    <div class="card card-content">
        <div class="card-header">
            <div class="tabs">
                <input type="radio" name="tab-btn" id="tab-btn-1" value="" checked>
                <label for="tab-btn-1">File 1</label>
                <input type="radio" name="tab-btn" id="tab-btn-2" value="">
                <label for="tab-btn-2">File 2</label>
                <input type="radio" name="tab-btn" id="tab-btn-3" value="">
                <label for="tab-btn-3">File 3</label>

                <div id="content-1">
                    Content 1
                </div>
                <div id="content-2">
                    Content 2
                </div>
                <div id="content-3">
                    Content 3
                </div>
            </div>
        </div>
    </div>
</div>

Explorer/Views/TreeModel/Tree.cshtml
<!-- 2 load the theme CSS file -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
<!-- 4 include the jQuery library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
<!-- 5 include the minified jstree source -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>

<html>
<head>
    <meta charset="utf-8">
    <title>jsTree test</title>

</head>
<body>

</body>
</html>